server:
  port: 8080


spring:
  config:
    import: optional:classpath:application-dev.yaml
  #MongoDB连接配置
  data:
    mongodb:
      uri: ${app.mongodb.uri}

  ##MySQL连接配置
  datasource:
    url: ${app.datasource.url}
    username: ${app.datasource.username}
    password: ${app.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
# mp开启 SQL 日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




langchain4j:
  open-ai:
    chat-model:
#      base-url: http://langchain4j.dev/demo/openai/v1
#      api-key: demo
#      model-name: gpt-4o-mini

      #阿里云百炼接入deepseek
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${app.langchain4j.open-ai.api-key}
      model-name: deepseek-v4-pro

      #程序发送给大模型的请求日志和响应日志
      log-requests: true
      log-responses: true

  #阿里云接入千问大模型
  community:
    dashscope:
      chat-model:
        api-key: ${app.langchain4j.dashscope.api-key}
        model-name: qwen-max

      streaming-chat-model:
        api-key: ${app.langchain4j.dashscope.api-key}
        model-name: qwen-max

      #集成阿里通义千问-通用文本向量-v3
      embedding-model:
        api-key: ${app.langchain4j.dashscope.api-key}
        model-name: text-embedding-v3
  # The properties are the same as `QwenChatModel`
  # e.g.
  # langchain4j.community.dashscope.chat-model.temperature=0.7
  # langchain4j.community.dashscope.chat-model.max-tokens=4096


#设置系统日志
logging:
  level:
    root: info


#Pinecone数据向量库API秘钥
pinecone:
  api-key: ${app.pinecone.api-key}
